/-
Copyright (c) 2026 Elazar Gershuni. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Elazar Gershuni
-/
module

public import Maths.Multitubes.PotentialRigidity

/-!
# Component and rooted-path normal forms for transport

Flat monoid transport is a unit-valued coboundary on each strongly connected
component.  Edges between distinct components are unconstrained because they
occur in no closed walk.  For group-valued labels, an arbitrary rooted path
family reduces flatness to the edges not generated by the chosen paths.  The
path family need not be an arborescence.

## Main definitions

* `Maths.HasSCCUnitPotentialAt` and `Maths.HasSCCUnitPotentials`:
  the labelling is a unit-valued coboundary on one component, respectively on every
  component.
* `Maths.sccUnitPotential`: the componentwise potential built from flat labels.
* `Maths.RootedPathFamily` and
  `Maths.RootedPathFamily.IsGeneratedEdge`: a family of walks out of a root,
  and the edges it already accounts for.

## Main results

* `Maths.hasTrivialCycleLabels_iff_hasSCCUnitPotentials`: flatness is exactly
  the componentwise coboundary normal form.
* `Maths.RootedPathFamily.label_mul_pathLabel_eq_of_isGeneratedEdge`: generated
  edges satisfy the coboundary equation automatically.
* `Maths.RootedPathFamily.hasTrivialCycleLabels_iff_nonGeneratedEdges`: for
  group-valued labels, flatness reduces to the non-generated edges.
* `Maths.hasTrivialCycleLabels_iff_chosen_return_nonGeneratedEdges`: the same
  reduction over a directly finite monoid, using chosen return walks.
-/

@[expose] public section

noncomputable section

namespace Maths

universe uV uE uM

variable {V : Type uV} {E : Type uE} {M : Type uM}
variable {G : EdgeGraph V E} {label : E → M}

section Monoid

variable [Monoid M]

/-- A unit potential local to the strongly connected component of `base`.
Only edges whose endpoints lie in that component are constrained. -/
def HasSCCUnitPotentialAt (G : EdgeGraph V E) (label : E → M)
    (base : V) : Prop :=
  ∃ potential : V → Mˣ, ∀ edge : E,
    LinkedTo G base (G.source edge) →
    LinkedTo G base (G.target edge) →
      label edge =
        (potential (G.target edge) *
          (potential (G.source edge))⁻¹ : Mˣ)

/-- Unit-potential normal form on every strongly connected component. -/
def HasSCCUnitPotentials (G : EdgeGraph V E) (label : E → M) : Prop :=
  ∀ base : V, HasSCCUnitPotentialAt G label base

/-- A canonical unit obtained from chosen forward and return walks inside one
strongly connected component. -/
def sccUnitPotential (hflat : HasTrivialCycleLabels G label)
    (base vertex : V) : Mˣ := by
  classical
  exact if hlinked : LinkedTo G base vertex then
      { val := walkLabel label hlinked.1.some
        inv := walkLabel label hlinked.2.some
        val_inv := by
          simpa using hflat vertex
            (hlinked.2.some.append hlinked.1.some)
        inv_val := by
          simpa using hflat base
            (hlinked.1.some.append hlinked.2.some) }
    else 1

private theorem sccUnitPotential_spec
    (hflat : HasTrivialCycleLabels G label) (base : V) (edge : E)
    (hsource : LinkedTo G base (G.source edge))
    (htarget : LinkedTo G base (G.target edge)) :
    label edge =
      (sccUnitPotential hflat base (G.target edge) *
        (sccUnitPotential hflat base (G.source edge))⁻¹ : Mˣ) := by
  classical
  let sourcePath := hsource.1.some
  let sourceReturn := hsource.2.some
  let targetPath := htarget.1.some
  let targetReturn := htarget.2.some
  have hparallel := walkLabel_eq_of_trivialCycleLabels_of_return hflat
    (sourcePath.concat edge rfl) targetPath targetReturn
  simp only [walkLabel_concat] at hparallel
  have hpathReturn :
      walkLabel label sourcePath * walkLabel label sourceReturn = 1 := by
    simpa using hflat (G.source edge) (sourceReturn.append sourcePath)
  simp only [sccUnitPotential, dif_pos htarget, dif_pos hsource]
  change label edge = walkLabel label targetPath * walkLabel label sourceReturn
  calc
    label edge = label edge *
        (walkLabel label sourcePath * walkLabel label sourceReturn) := by
      rw [hpathReturn, mul_one]
    _ = (label edge * walkLabel label sourcePath) *
        walkLabel label sourceReturn := by rw [mul_assoc]
    _ = walkLabel label targetPath * walkLabel label sourceReturn := by
      rw [hparallel]

private theorem walkLabel_eq_unitPotential_on_edges
    (potential : V → Mˣ) {start finish : V}
    (walk : G.Walk start finish)
    (hedge : ∀ edge ∈ walk.edges,
      label edge =
        (potential (G.target edge) *
          (potential (G.source edge))⁻¹ : Mˣ)) :
    walkLabel label walk =
      (potential finish * (potential start)⁻¹ : Mˣ) := by
  induction walk with
  | nil => simp
  | @concat middle walk edge legal ih =>
      have hbefore (candidate : E) (hcandidate : candidate ∈ walk.edges) :
          label candidate =
            (potential (G.target candidate) *
              (potential (G.source candidate))⁻¹ : Mˣ) :=
        hedge candidate (by simp [hcandidate])
      have hfinal := hedge edge (by simp)
      rw [walkLabel_concat, hfinal, ih hbefore, legal]
      have hunits :
          (potential (G.target edge) * (potential middle)⁻¹) *
              (potential middle * (potential start)⁻¹) =
            potential (G.target edge) * (potential start)⁻¹ := by
        simp
      change ((↑((potential (G.target edge) * (potential middle)⁻¹) *
          (potential middle * (potential start)⁻¹)) : M)) =
        ((↑(potential (G.target edge) * (potential start)⁻¹) : M))
      exact congrArg (fun unit : Mˣ => (unit : M)) hunits

private theorem linkedTo_of_mem_cycle_source {base : V}
    (cycle : G.Walk base base) {edge : E} (hedge : edge ∈ cycle.edges) :
    LinkedTo G base (G.source edge) := by
  let split := cycle.vertexSplitAtSource edge hedge
  exact ⟨⟨split.before⟩, ⟨split.after⟩⟩

private theorem linkedTo_of_mem_cycle_target {base : V}
    (cycle : G.Walk base base) {edge : E} (hedge : edge ∈ cycle.edges) :
    LinkedTo G base (G.target edge) := by
  let split := cycle.vertexSplitAtTarget edge hedge
  exact ⟨⟨split.before⟩, ⟨split.after⟩⟩

/-- **SCC normal form.**  A monoid labelling is flat exactly when it is a
unit-valued coboundary separately on every strongly connected component.
No condition is imposed on inter-component edges. -/
theorem hasTrivialCycleLabels_iff_hasSCCUnitPotentials :
    HasTrivialCycleLabels G label ↔ HasSCCUnitPotentials G label := by
  constructor
  · intro hflat base
    refine ⟨sccUnitPotential hflat base, ?_⟩
    intro edge hsource htarget
    exact sccUnitPotential_spec hflat base edge hsource htarget
  · intro hcomponents base cycle
    obtain ⟨potential, hpotential⟩ := hcomponents base
    have hedge (edge : E) (hmem : edge ∈ cycle.edges) :
        label edge =
          (potential (G.target edge) *
            (potential (G.source edge))⁻¹ : Mˣ) :=
      hpotential edge
        (linkedTo_of_mem_cycle_source cycle hmem)
        (linkedTo_of_mem_cycle_target cycle hmem)
    rw [walkLabel_eq_unitPotential_on_edges potential cycle hedge]
    simp

end Monoid

/-! ## Rooted path-family tests for group labels -/

section Group

variable [Group M]

/-- A rooted family of chosen paths.  The structure imposes no acyclicity,
simplicity, coherence, or arborescence invariant. -/
structure RootedPathFamily (G : EdgeGraph V E) (base : V) where
  path : ∀ vertex : V, G.Walk base vertex

namespace RootedPathFamily

/-- Edges generated by one-step extension of the chosen rooted paths. -/
def IsGeneratedEdge {base : V} (family : RootedPathFamily G base)
    (edge : E) : Prop :=
  family.path (G.target edge) =
    (family.path (G.source edge)).concat edge rfl

private def groupUnit (value : M) : Mˣ where
  val := value
  inv := value⁻¹
  val_inv := mul_inv_cancel value
  inv_val := inv_mul_cancel value

private def potential {base : V} (family : RootedPathFamily G base)
    (label : E → M) (vertex : V) : Mˣ :=
  groupUnit (walkLabel label (family.path vertex))

/-- Generated edges satisfy the path-potential equation definitionally. -/
theorem label_mul_pathLabel_eq_of_isGeneratedEdge {base : V}
    (family : RootedPathFamily G base) {edge : E}
    (hgenerated : family.IsGeneratedEdge edge) :
    label edge * walkLabel label (family.path (G.source edge)) =
      walkLabel label (family.path (G.target edge)) := by
  rw [hgenerated, walkLabel_concat]

/-- **Rooted path-family test.**  Once rooted paths are fixed, equations on
one-step extensions are automatic.  Flatness is equivalent to checking the
path-potential equation on all other edges. -/
theorem hasTrivialCycleLabels_iff_nonGeneratedEdges {base : V}
    (hconnected : IsStronglyConnectedAt G base)
    (family : RootedPathFamily G base) :
    HasTrivialCycleLabels G label ↔
      ∀ edge : E, ¬family.IsGeneratedEdge edge →
        label edge * walkLabel label (family.path (G.source edge)) =
          walkLabel label (family.path (G.target edge)) := by
  constructor
  · intro hflat edge _
    exact (hasTrivialCycleLabels_iff_parallelLabels hconnected).mp hflat
      ((family.path (G.source edge)).concat edge rfl)
      (family.path (G.target edge))
  · intro hnongenerated
    let p : V → Mˣ := family.potential label
    apply hasTrivialCycleLabels_of_unitPotential p
    intro edge
    have hedge :
        label edge * walkLabel label (family.path (G.source edge)) =
          walkLabel label (family.path (G.target edge)) := by
      by_cases hgenerated : family.IsGeneratedEdge edge
      · exact family.label_mul_pathLabel_eq_of_isGeneratedEdge hgenerated
      · exact hnongenerated edge hgenerated
    change label edge =
      walkLabel label (family.path (G.target edge)) *
        (walkLabel label (family.path (G.source edge)))⁻¹
    calc
      label edge =
          (label edge * walkLabel label (family.path (G.source edge))) *
            (walkLabel label (family.path (G.source edge)))⁻¹ := by simp
      _ = walkLabel label (family.path (G.target edge)) *
          (walkLabel label (family.path (G.source edge)))⁻¹ := by rw [hedge]

end RootedPathFamily

end Group

section DirectlyFiniteMonoid

variable [Monoid M] [IsDedekindFiniteMonoid M]

/-- **Directly-finite rooted path-family test.**  Given arbitrary root paths
and return paths, global flatness is equivalent to the return identities and
the edge-loop identities outside the one-step extensions generated by the
chosen root paths.  Equations on generated edges follow automatically from
the corresponding return identity. -/
theorem hasTrivialCycleLabels_iff_chosen_return_nonGeneratedEdges {base : V}
    (family : RootedPathFamily G base)
    (returns : ∀ vertex, G.Walk vertex base) :
    HasTrivialCycleLabels G label ↔
      (∀ vertex,
        walkLabel label (returns vertex) *
          walkLabel label (family.path vertex) = 1) ∧
      ∀ edge, ¬family.IsGeneratedEdge edge →
        walkLabel label (returns (G.target edge)) * label edge *
          walkLabel label (family.path (G.source edge)) = 1 := by
  constructor
  · intro hflat
    refine ⟨fun vertex => ?_, fun edge _ => ?_⟩
    · simpa using hflat base
        ((family.path vertex).append (returns vertex))
    · simpa [mul_assoc] using hflat base
        (((family.path (G.source edge)).concat edge rfl).append
          (returns (G.target edge)))
  · rintro ⟨hreturn, hnongenerated⟩
    apply hasTrivialCycleLabels_of_chosen_tests family.path returns hreturn
    intro edge
    by_cases hgenerated : family.IsGeneratedEdge edge
    · have hedge : label edge *
          walkLabel label (family.path (G.source edge)) =
            walkLabel label (family.path (G.target edge)) := by
        rw [hgenerated, walkLabel_concat]
      calc
        walkLabel label (returns (G.target edge)) * label edge *
            walkLabel label (family.path (G.source edge)) =
            walkLabel label (returns (G.target edge)) *
              (label edge *
                walkLabel label (family.path (G.source edge))) := by
              rw [mul_assoc]
        _ = walkLabel label (returns (G.target edge)) *
            walkLabel label (family.path (G.target edge)) := by rw [hedge]
        _ = 1 := hreturn (G.target edge)
    · exact hnongenerated edge hgenerated

end DirectlyFiniteMonoid

end Maths

end
