/-
Copyright (c) 2026 Elazar Gershuni. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Elazar Gershuni
-/
module

public import WebOfTrust.ProvenanceTransport

/-!
# Web-of-trust evidence transport

Endorsement edges transport sets of provenance-bearing evidence records. Sound global evidence
assignments are lax sections, and path closure gives the least sound assignment above trusted
seed evidence.

## Main definitions

* `WebOfTrust.evidenceTransport` - endorsement transport on evidence sets.
* `WebOfTrust.IsSoundAssignment` - local closure under every endorsement.
* `WebOfTrust.soundClosure` - evidence generated by all endorsement chains.

## Main results

* `WebOfTrust.chainEvidence_le_of_isSound` - local soundness propagates along chains.
* `WebOfTrust.mem_soundClosure_iff` - closure membership has a path witness.
* `WebOfTrust.soundClosure_isLeast` - path closure is the least sound assignment containing
  the seed evidence.

## Tags

web of trust, endorsement, provenance, evidence, path closure, lax section
-/

@[expose] public section

namespace WebOfTrust

end WebOfTrust
